<?php

$form = $this->form;
$fieldset = $form->get('group');

$groupId = $fieldset->get('groupId');
$name = $fieldset->get('name');

$submit = $form->get('submit');
$submit->setValue($this->submitLabel);
$submit->setAttribute('class', 'btn btn-primary');

$form->prepare();

echo $this->form()->openTag($form);
?>
  
  <fieldset>
    <div class="form-group">
      <?= $this->formLabel($name) ?>
      <?= $this->formElement($name) ?>
      <?= $this->formElementErrors()->render($name, ['class' => 'help-block']) ?>
    </div>
  </fieldset>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($groupId);
echo $this->form()->closeTag();